/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { LockedFunds } from "./LockedFunds";
import { LockedFundsCountArgs } from "./LockedFundsCountArgs";
import { LockedFundsFindManyArgs } from "./LockedFundsFindManyArgs";
import { LockedFundsFindUniqueArgs } from "./LockedFundsFindUniqueArgs";
import { CreateLockedFundsArgs } from "./CreateLockedFundsArgs";
import { UpdateLockedFundsArgs } from "./UpdateLockedFundsArgs";
import { DeleteLockedFundsArgs } from "./DeleteLockedFundsArgs";
import { Wallet } from "../../wallet/base/Wallet";
import { LockedFundsService } from "../lockedFunds.service";
@graphql.Resolver(() => LockedFunds)
export class LockedFundsResolverBase {
  constructor(protected readonly service: LockedFundsService) {}

  async _lockedFundsItemsMeta(
    @graphql.Args() args: LockedFundsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [LockedFunds])
  async lockedFundsItems(
    @graphql.Args() args: LockedFundsFindManyArgs
  ): Promise<LockedFunds[]> {
    return this.service.lockedFundsItems(args);
  }

  @graphql.Query(() => LockedFunds, { nullable: true })
  async lockedFunds(
    @graphql.Args() args: LockedFundsFindUniqueArgs
  ): Promise<LockedFunds | null> {
    const result = await this.service.lockedFunds(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => LockedFunds)
  async createLockedFunds(
    @graphql.Args() args: CreateLockedFundsArgs
  ): Promise<LockedFunds> {
    return await this.service.createLockedFunds({
      ...args,
      data: {
        ...args.data,

        wallet: args.data.wallet
          ? {
              connect: args.data.wallet,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => LockedFunds)
  async updateLockedFunds(
    @graphql.Args() args: UpdateLockedFundsArgs
  ): Promise<LockedFunds | null> {
    try {
      return await this.service.updateLockedFunds({
        ...args,
        data: {
          ...args.data,

          wallet: args.data.wallet
            ? {
                connect: args.data.wallet,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => LockedFunds)
  async deleteLockedFunds(
    @graphql.Args() args: DeleteLockedFundsArgs
  ): Promise<LockedFunds | null> {
    try {
      return await this.service.deleteLockedFunds(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Wallet, {
    nullable: true,
    name: "wallet",
  })
  async getWallet(
    @graphql.Parent() parent: LockedFunds
  ): Promise<Wallet | null> {
    const result = await this.service.getWallet(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
